### PR TITLE
Update description and Rbuildignore file

### PR DESCRIPTION
**Pull request by zhanxw**
* Checked MicrobiotaProcess worked for R 3.5.0
* Update Rbuildignore  to avoid warnings when check/build this package

### CODE REVIEW

**Comment by xiangpin** [comment]
Thanks for your attention, but MicrobiotaProcess is reviewing to submit Biocondutor. It need to be checked under R-devel, according to the rule of Bioconductor. So I can't merge the request.

**Comment by zhanxw** [comment]
That is different: check under R-devel and require R-devel.
For `check under R-devel`, the developer will use the latest R software to run `R CMD check`.
For `require R-devel`, all users will have to use the R 4.0 version. That is probably hard.

See: https://github.com/YuLab-SMU/ggtree/blob/master/DESCRIPTION
ggtree is a Bioconductor package, and it requires R >=3.4.0

**Comment by xiangpin** [comment]
MicrobiotaProcess is first submitted to Bioconductor. I set R >=3.6.0 before, but the report of BiocCheck has warning. When the R version was changed to 4.0, the warning was removed.  And I will change the R version when MicrobiotaProcess is accepted by Bioconductor. Thanks!

**Comment by zhanxw** [comment]
Thanks for letting me know this experience.

**Pull request closed without merging**
